### ISSUE TITLE
Set up a "help" command for the bot 

### ISSUE THREAD

**Issue by JonesZachary** [CSI-280/Pandoras-Bot#3]
Add a help command (something like "-h") that creates a list of all the commands and actions that users can have the bot do. The help hotkey should probably also be in the bot's description so we all know what it is. 

The list of commands to add to this list can be found in the google doc here: 
https://docs.google.com/document/d/1ivIWoKb3R_nIr4qHcLMr1CVFpb9hlSCrnFK6DW6I5d0/edit?usp=sharing

**Comment by JonesZachary** [comment]
It's not necessary to write the code for this right now, maybe just create a template for the text that will be displayed.

**Comment by Gumbachi** [comment]
PR #8 completes this
